### ISSUE TITLE
Cannot find module declaration Typescript Issue (.patch fix)

### ISSUE THREAD

**Issue by MatteoGauthier** [huijiewei/cache-manager-sqlite#1]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@resolid/cache-manager-sqlite@5.0.0` for the project I'm working on.

I have TS issues with your package 
![Capture d’écran 2024-04-29 à 14 03 13](https://github.com/huijiewei/cache-manager-sqlite/assets/32040951/959c99e7-0fe9-4618-9afb-3959acf2ac4a)

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@resolid/cache-manager-sqlite/package.json b/node_modules/@resolid/cache-manager-sqlite/package.json
index fab3837..0826085 100644
--- a/node_modules/@resolid/cache-manager-sqlite/package.json
+++ b/node_modules/@resolid/cache-manager-sqlite/package.json
@@ -11,23 +11,20 @@
   "sideEffects": false,
   "type": "module",
   "author": "Huijie Wei",
+  "main": "dist/index.js",
+  "types": "dist/index.d.ts",
   "publishConfig": {
     "access": "public"
   },
   "files": [
-    "dist"
+    "dist/**/*.js",
+    "dist/**/*.d.ts"
   ],
   "scripts": {
     "build": "tsup",
     "test": "vitest --ui",
     "format": "biome format ./src"
   },
-  "exports": {
-    ".": {
-      "import": "./dist/index.js",
-      "types": "./dist/index.d.ts"
-    }
-  },
   "devDependencies": {
     "@faker-js/faker": "^8.4.0",
     "@types/better-sqlite3": "^7.6.9",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by huijiewei** [comment]
thanks for your report. i upgrade package to 5.1.0 to fix this problem.

verfiy: 

https://arethetypeswrong.github.io/?p=%40resolid%2Fcache-manager-sqlite%405.1.0

and

https://publint.dev/@resolid/cache-manager-sqlite@5.1.0
