### ISSUE TITLE
Warn about cache-manager@^6

### ISSUE THREAD

**Issue by Oscaner** [huijiewei/cache-manager-sqlite#7]
<img width="791" alt="image" src="https://github.com/user-attachments/assets/5d6dc49e-ecd5-47ee-87d0-fda8c54bc9b3">

Hi @huijiewei, can you please upgrade the package.json to support cache-manager larger than 6 version?

**Comment by huijiewei** [comment]
cache-manager v6 are using Keyv

**Comment by huijiewei** [comment]
https://github.com/huijiewei/keyv-sqlite
